name: pin_code_fields
description: A flutter package which will help you to generate pin code fields. Can be useful for OTP for example.
version: 8.0.1
homepage: https://github.com/adar2378
repository: https://github.com/adar2378/pin_code_fields

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
